# Simple Workflow to print environment based on branch

on:
  push:
    branches: [ master, develop, stage ]
  repository_dispatch:    
    type: [repo-dispatch]  

name: Test Github Actions

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: [self-hosted, linux]

    steps:  
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Set default ENVIRONMENT
      shell: bash
      run: |
        echo "ENVIRONMENT=development" >> $GITHUB_ENV

    - name: Set ENVIRONMENT & CLUSTOR for develop
      if: endsWith(github.ref, '/develop')
      run: |
        echo "ENVIRONMENT=development" >> $GITHUB_ENV
       
    - name: Set ENVIRONMENT & CLUSTOR for uat
      if: endsWith(github.ref, '/stage')
      run: |
        echo "ENVIRONMENT=uat" >> $GITHUB_ENV
       
    - name: Set ENVIRONMENT & CLUSTOR for production
      if: endsWith(github.ref, '/master')
      run: |
        echo "ENVIRONMENT=production" >> $GITHUB_ENV
